apiVersion: v1
kind: ConfigMap
metadata:
  name: coworking-postgresql
  #name: <SERVICE_NAME>-postgresql

data:
  DB_NAME: "deandatabase"
  DB_USERNAME: "dean"
  DB_HOST: "postgresql-service"
  DB_PORT: "5432"
---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: "deansecret"
# type: Opaque
# data:
#   password: "cGFzc3dvcmQxMjM"